### ISSUE TITLE
Program does not start

### ISSUE THREAD

**Issue by vomo1** [AK-Homberger/Alexa-Alarm-System-ESP32CAM#2]
Hello,
I tried to use this wonderful sketch, but it does not work at my configuration.

Sample CAM program on ESP32 works, this one gives the following output in terminal:
```
rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
E (1069) SPIFFS: mount failed, -10025
ets Jun  8 2016 00:22:57

rst:0x8 (TG1WDT_SYS_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1240
load:0x40078000,len:13012
load:0x40080400,len:3648
entry 0x400805f8
E (1069) SPIFFS: mount failed, -10025
ets Jun  8 2016 00:22:57
```
Can someone figure out what I´m doing wrong?
Thanks!
Steff

**Comment by AK-Homberger** [comment]
Hi Steff,

Please make sure you are using the right board and  partition scheme. Its different from Sample CAM.

Here we need: 

    Board: ESP32 Wrover Module
    Partition scheme: Default 4MB with spiffs...

Spiffs is needed to sotore the pictures in flash memory.

Regards,
Andreas

**Comment by vomo1** [comment]
Hi Andreas,
thanks for your quick reply!

I checked the the board and partition information, it is correct. 
I tried a second board, same mistake.
It also did not work with other partition specifications.
Unfortunately, my experience in this area is too limited...

Best regards,
Steff

**Comment by vomo1** [comment]
OK, problem solved:

Follow these instructions, after that it was functional!

https://github.com/me-no-dev/arduino-esp32fs-plugin

Best regards & thanks!
Steff

**Comment by AK-Homberger** [comment]
Hi Steff,
Good to know that this solution worked for you. But on a clean installead Arduino IDE this step is not necessary.
Some instructions for the ESP32-CAM requires to manually change the partition information in the configuration files. This is not good parctice because it might have problematic side effects.
The above plugin probably changed the partition information again to a working state.
Regards,
Andreas
